### ISSUE TITLE
keyPrefix needed for the agents registry key to be shared across all agents.

### ISSUE THREAD

**Issue by Cyb3rWard0g** [bibryam/calculator-agent#1]
For Agents registry to be shared and not create one per agent, you need to set

```
    - name: keyPrefix
      value: none
```

as shown below

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: agentstatestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: keyPrefix
      value: none
```

Needs to be added here: https://github.com/bibryam/calculator-agent/blob/main/components/agentstatestore.yaml
